# -*- coding: utf-8 -*-
"""Smartwatch_Data_Analysis.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ySuK_g5KRXdqvoQcoXmfxet_vYHMhv1N
"""

import pandas as pd
df=pd.read_csv('/content/dailyActivity_merged.csv')
df

df.columns

df.info()

df.head()

df.tail()

#The 'ActivityDate' is an object datatype.So let's convert this column into a datetime column

df['ActivityDate'] = pd.to_datetime(df['ActivityDate'],format="%m/%d/%Y")

#Let's combine all the Minutes columns to a single column

df['TotalMinutes'] = df['VeryActiveMinutes']+df['FairlyActiveMinutes']+df['LightlyActiveMinutes']+df['SedentaryMinutes']

df['TotalMinutes'].head()

df.describe()

import seaborn as sns
sns.lineplot(data= df,x='ActivityDate',y='Calories')

# Let's data has converted in to min
df[df['Calories']==df['Calories'].min()]

#Let's data has converted in to
df[df['Calories']==df['Calories'].max()]

df[df['Calories']==df['Calories'].min()]

sns.barplot(data=df,x='Calories'	,y='ActivityDate')

#Let's analyze! dataset has a 'Calories' column , which stores the number of calories burned in a day. Let's look at the relationship between calories burned and the total steps walked in a day

import plotly.express as px
fig1 = px.scatter(data_frame=df,x='Calories',y='TotalSteps',trendline='ols',title='Relationship b/w Calories & Total steps')
fig1.show()

